name: Continuous Integration
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn test

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: false
          browser: chrome
          headless: true
          config: baseUrl=http://localhost:3000
          build: npm run build
          start: npm start
